// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: holidays.proto

package gRPC.Project.SmartOffice;

public interface BalanceReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:holidays.BalanceReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 balance = 1;</code>
   */
  int getBalance();
}
