// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profiling.proto

package gRPC.Project.SmartOffice;

public interface eListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:profiling.eListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
