// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profiling.proto

package gRPC.Project.SmartOffice;

public interface eListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:profiling.eListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string job = 3;</code>
   */
  java.lang.String getJob();
  /**
   * <code>string job = 3;</code>
   */
  com.google.protobuf.ByteString
      getJobBytes();

  /**
   * <code>bool busy = 4;</code>
   */
  boolean getBusy();

  /**
   * <code>string task = 5;</code>
   */
  java.lang.String getTask();
  /**
   * <code>string task = 5;</code>
   */
  com.google.protobuf.ByteString
      getTaskBytes();
}
