// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: holidays.proto

package gRPC.Project.SmartOffice;

public final class HolidayService {
  private HolidayService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_holidays_IdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_holidays_IdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_holidays_BalanceReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_holidays_BalanceReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016holidays.proto\022\010holidays\"\027\n\tIdRequest\022" +
      "\n\n\002id\030\001 \001(\005\"\037\n\014BalanceReply\022\017\n\007balance\030\001" +
      " \001(\0052M\n\016TimeOffService\022;\n\ngetBalance\022\023.h" +
      "olidays.IdRequest\032\026.holidays.BalanceRepl" +
      "y\"\000B,\n\030gRPC.Project.SmartOfficeB\016Holiday" +
      "ServiceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_holidays_IdRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_holidays_IdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_holidays_IdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_holidays_BalanceReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_holidays_BalanceReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_holidays_BalanceReply_descriptor,
        new java.lang.String[] { "Balance", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
