// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: holidays.proto

package gRPC.Project.SmartOffice;

public interface IdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:holidays.IdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
