// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bugs.proto

package gRPC.Project.SmartOffice;

public interface ListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bugs.ListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 quantity = 1;</code>
   */
  int getQuantity();
}
