// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bugs.proto

package gRPC.Project.SmartOffice;

public interface ListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bugs.ListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 1;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string details = 2;</code>
   */
  java.lang.String getDetails();
  /**
   * <code>string details = 2;</code>
   */
  com.google.protobuf.ByteString
      getDetailsBytes();

  /**
   * <code>int32 severity = 3;</code>
   */
  int getSeverity();

  /**
   * <code>string reportedBy = 4;</code>
   */
  java.lang.String getReportedBy();
  /**
   * <code>string reportedBy = 4;</code>
   */
  com.google.protobuf.ByteString
      getReportedByBytes();
}
