// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profiling.proto

package gRPC.Project.SmartOffice;

public interface LogRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:profiling.LogRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
