// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bugs.proto

package gRPC.Project.SmartOffice;

public interface NewBugsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bugs.NewBugs)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 1;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string details = 2;</code>
   */
  java.lang.String getDetails();
  /**
   * <code>string details = 2;</code>
   */
  com.google.protobuf.ByteString
      getDetailsBytes();

  /**
   * <pre>
   *	string reportedBy = 4;
   * </pre>
   *
   * <code>int32 severity = 3;</code>
   */
  int getSeverity();
}
