// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profiling.proto

package gRPC.Project.SmartOffice;

public final class ProfileService {
  private ProfileService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profiling_LogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profiling_LogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profiling_LogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profiling_LogResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profiling_eListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profiling_eListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_profiling_eListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_profiling_eListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017profiling.proto\022\tprofiling\",\n\nLogReque" +
      "st\022\014\n\004name\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"/\n\013Lo" +
      "gResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002 " +
      "\001(\t\"\032\n\014eListRequest\022\n\n\002id\030\001 \001(\005\"R\n\reList" +
      "Response\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\013\n\003jo" +
      "b\030\003 \001(\t\022\014\n\004busy\030\004 \001(\010\022\014\n\004task\030\005 \001(\0052\343\001\n\020" +
      "ProfilingService\0228\n\005logIn\022\025.profiling.Lo" +
      "gRequest\032\026.profiling.LogResponse\"\000\022H\n\017ge" +
      "tEmployeeList\022\027.profiling.eListRequest\032\030" +
      ".profiling.eListResponse\"\0000\001\022K\n\022getAllEm" +
      "ployeeList\022\027.profiling.eListRequest\032\030.pr" +
      "ofiling.eListResponse\"\0000\001B,\n\030gRPC.Projec" +
      "t.SmartOfficeB\016ProfileServiceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_profiling_LogRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_profiling_LogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profiling_LogRequest_descriptor,
        new java.lang.String[] { "Name", "Password", });
    internal_static_profiling_LogResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_profiling_LogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profiling_LogResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_profiling_eListRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_profiling_eListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profiling_eListRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_profiling_eListResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_profiling_eListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_profiling_eListResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Job", "Busy", "Task", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
